---
abstract: 'Generic TCP server'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-Server-TCP
no_index:
  directory:
    - t
    - inc
requires:
  IO::Socket::SSL: 1.962
  Net::SSLeay: 1.55
  URI: 1.60
  URI::Escape: 3.31
resources:
  bugtracker: https://github.com/jhthorsen/mojo-server-tcp/issues
  homepage: https://metacpan.org/release/Mojo-Server-TCP
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jhthorsen/mojo-server-tcp.git
version: 0.01
